# Generated by Django 3.0.8 on 2020-07-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='classroom_id',
            field=models.IntegerField(default=-1),
        ),
    ]
