# Generated by Django 3.0.8 on 2020-07-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_notice_classroom_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
