# Generated by Django 3.0.8 on 2020-07-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='submit_at',
            field=models.DateTimeField(),
        ),
    ]
