# Generated by Django 3.0.8 on 2020-07-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200718_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('class_name', models.CharField(max_length=50, null=True)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Classroom')),
            ],
        ),
    ]
