# Generated by Django 3.0.8 on 2020-07-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200718_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='title',
        ),
    ]
