# Generated by Django 3.0.8 on 2020-07-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_classroom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='classroom_id',
            field=models.IntegerField(),
        ),
    ]
