# Generated by Django 3.0.8 on 2020-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200719_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='submit_at',
            field=models.DateTimeField(null=True),
        ),
    ]
