# Generated by Django 3.0.8 on 2020-07-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200719_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
