# Generated by Django 3.0.8 on 2020-07-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_attend_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='obj_code',
            new_name='sbj_code',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='obj_name',
            new_name='sbj_name',
        ),
    ]
