# Generated by Django 3.0.8 on 2020-07-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200720_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='sbj_code',
            field=models.IntegerField(null=True),
        ),
    ]
