# Generated by Django 3.0.8 on 2020-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_refer'),
    ]

    operations = [
        migrations.AddField(
            model_name='refer',
            name='notice_id',
            field=models.IntegerField(null=True),
        ),
    ]
